# Generated by Django 5.0.3 on 2025-03-19 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nm_descritivo', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('valor_padrao', models.FloatField(null=True)),
            ],
            options={
                'db_table': '"public"."exame"',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, null=True)),
                ('codigo_externo', models.CharField(max_length=100, null=True)),
                ('informacao', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': '"public"."tipo"',
            },
        ),
        migrations.CreateModel(
            name='ExameExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.IntegerField(null=True)),
                ('work', models.CharField(max_length=100, null=True)),
                ('paciente', models.CharField(max_length=100, null=True)),
                ('tutor', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('valor', models.FloatField(null=True)),
                ('exame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exames.exame')),
                ('laudo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exames.tipo')),
            ],
            options={
                'db_table': '"public"."exame_execucao"',
            },
        ),
    ]
