# Generated by Django 5.0.3 on 2025-03-19 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exameexecucao',
            name='doper',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exameexecucao',
            name='especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='especie', to='exames.tipo'),
        ),
        migrations.AlterField(
            model_name='exameexecucao',
            name='laudo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='laudo', to='exames.tipo'),
        ),
    ]
