# Generated by Django 5.0.3 on 2025-03-29 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0002_exameexecucao_doper_exameexecucao_especie_and_more'),
        ('funcionario', '0008_filialfuncionario_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='exameexecucao',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='especie', to='funcionario.filial'),
        ),
    ]
