# Generated by Django 5.0.3 on 2025-04-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_exameexecucao_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exameexecucao',
            name='exame',
        ),
        migrations.RemoveField(
            model_name='exameexecucao',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='exameexecucao',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='exameexecucao',
            name='laudo',
        ),
        migrations.DeleteModel(
            name='Exame',
        ),
        migrations.DeleteModel(
            name='ExameExecucao',
        ),
    ]
