# Generated by Django 5.0.3 on 2025-04-14 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0004_remove_exameexecucao_exame_and_more'),
        ('funcionario', '0009_funcionario_senha_padrão'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nm_descritivo', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('valor_padrao', models.FloatField(null=True)),
            ],
            options={
                'db_table': '"public"."exame"',
            },
        ),
        migrations.CreateModel(
            name='ExameExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.IntegerField(null=True)),
                ('work', models.CharField(max_length=100, null=True)),
                ('doper', models.BigIntegerField(null=True)),
                ('paciente', models.CharField(max_length=100, null=True)),
                ('tutor', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('valor', models.FloatField(null=True)),
                ('especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='especie', to='exames.tipo')),
                ('exame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exames.exame')),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='especie', to='funcionario.filial')),
                ('laudo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='laudo', to='exames.tipo')),
            ],
            options={
                'db_table': '"public"."exame_execucao"',
            },
        ),
    ]
