# Generated by Django 5.0.3 on 2025-03-18 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nm_descritivo', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('valor', models.FloatField(null=True)),
                ('nivel', models.IntegerField(null=True)),
            ],
            options={
                'db_table': '"public"."perfis"',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('matricula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('cpf', models.BigIntegerField()),
                ('nome', models.CharField(max_length=100, null=True)),
                ('sobrenome', models.CharField(max_length=100, null=True)),
                ('data_nascimento', models.IntegerField(null=True)),
                ('imagem', models.CharField(max_length=200, null=True)),
                ('codigo_recuperacao', models.BigIntegerField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('stack_aposta', models.FloatField(default=0.0, null=True)),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.perfis')),
            ],
            options={
                'db_table': '"public"."funcionario"',
            },
        ),
    ]
