# Generated by Django 5.0.3 on 2025-03-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_funcionario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='matricula',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
