# Generated by Django 5.0.3 on 2025-03-19 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_remove_funcionario_matricula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('nm_descritivo', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('valor', models.FloatField(null=True)),
                ('nivel', models.IntegerField(null=True)),
            ],
            options={
                'db_table': '"public"."filial"',
            },
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='stack_aposta',
        ),
        migrations.CreateModel(
            name='FilialFuncionario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.filial')),
            ],
            options={
                'db_table': '"public"."filial_funcionario"',
            },
        ),
    ]
