# Generated by Django 5.0.3 on 2025-03-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0004_filial_remove_funcionario_stack_aposta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='filialfuncionario',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='filialfuncionario',
            name='funcionario',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='username',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
