# Generated by Django 5.0.3 on 2025-03-19 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_remove_filial_nivel_remove_filial_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialfuncionario',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.filial'),
        ),
        migrations.AddField(
            model_name='filialfuncionario',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
