# Generated by Django 5.0.3 on 2025-03-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0006_filialfuncionario_filial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filialfuncionario',
            name='funcionario',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='username',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
