# Generated by Django 5.0.3 on 2025-04-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0008_filialfuncionario_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='senha_padrão',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
