# Generated by Django 5.0.3 on 2025-05-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0009_funcionario_senha_padrão'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='senha_padrão',
            new_name='senha_padrao',
        ),
    ]
