# Generated by Django 5.0.3 on 2025-05-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0010_rename_senha_padrão_funcionario_senha_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
